
import __ASTRO_IMAGE_IMPORT_2eXRkF from "../../assets/images/dopamine.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Frecompense.md";
import __ASTRO_IMAGE_IMPORT_Zs6FaD from "../../assets/images/dopamine.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fsyst-recompense-2.md";
import __ASTRO_IMAGE_IMPORT_Zs6xag from "../../assets/images/dopamine.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fsyst-recompense-3.md";
import __ASTRO_IMAGE_IMPORT_vstue from "../../assets/images/balance-plaisir-douleur.svg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fsyst-recompense-3.md";
import __ASTRO_IMAGE_IMPORT_Zs6p9S from "../../assets/images/dopamine.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fsyst-recompense-4.md";
import __ASTRO_IMAGE_IMPORT_vsBuB from "../../assets/images/balance-plaisir-douleur.svg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fsyst-recompense-4.md";
import __ASTRO_IMAGE_IMPORT_Z1nKiIx from "images/balance-plaisir-douleur.svg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fsyst-recompense-4.md";
import __ASTRO_IMAGE_IMPORT_Zs6h9v from "../../assets/images/dopamine.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fsyst-recompense-5.md";
import __ASTRO_IMAGE_IMPORT_vsJuY from "../../assets/images/balance-plaisir-douleur.svg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fsyst-recompense-5.md";
export default new Map([["../../assets/images/dopamine.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Frecompense.md", __ASTRO_IMAGE_IMPORT_2eXRkF], ["../../assets/images/dopamine.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fsyst-recompense-2.md", __ASTRO_IMAGE_IMPORT_Zs6FaD], ["../../assets/images/dopamine.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fsyst-recompense-3.md", __ASTRO_IMAGE_IMPORT_Zs6xag], ["../../assets/images/balance-plaisir-douleur.svg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fsyst-recompense-3.md", __ASTRO_IMAGE_IMPORT_vstue], ["../../assets/images/dopamine.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fsyst-recompense-4.md", __ASTRO_IMAGE_IMPORT_Zs6p9S], ["../../assets/images/balance-plaisir-douleur.svg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fsyst-recompense-4.md", __ASTRO_IMAGE_IMPORT_vsBuB], ["images/balance-plaisir-douleur.svg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fsyst-recompense-4.md", __ASTRO_IMAGE_IMPORT_Z1nKiIx], ["../../assets/images/dopamine.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fsyst-recompense-5.md", __ASTRO_IMAGE_IMPORT_Zs6h9v], ["../../assets/images/balance-plaisir-douleur.svg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fsyst-recompense-5.md", __ASTRO_IMAGE_IMPORT_vsJuY]]);
		